(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var U0=function(a){a.ea("cardstatechange",a.Lh()&&a.Rk()?1:0)},V0=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},jUa=function(a){var b=g.Lm(a);
a=g.Om(a);return new g.Am(b.x,b.y,a.width,a.height)},kUa=function(a){return Math.pow(a,3)},lUa=function(a){return 3*a*a-2*a*a*a},Y0=function(a){a=g.Sa(a);
delete W0[a];g.bg(W0)&&X0&&X0.stop()},nUa=function(){X0||(X0=new g.L(function(){mUa()},20));
var a=X0;a.isActive()||a.start()},mUa=function(){var a=g.Va();
g.Mf(W0,function(b){oUa(b,a)});
g.bg(W0)||nUa()},Z0=function(a,b,c,d){g.Hp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},oUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;pUa(a,a.progress);1==a.progress?(a.j=0,Y0(a),a.onFinish(),a.Dx()):a.Jc()&&a.oD()},pUa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},qUa=function(a,b){g.Cf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$0=function(a,b,c,d,e){Z0.call(this,b,c,d,e);
this.element=a},a1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$0.call(this,a,b,c,d,e)},b1=function(a){g.G.call(this);
this.u=a||window;this.j=[]},c1=function(a){return a.baseUrl||null},d1=function(a,b){return g.Dn(g.Kl(a,b,void 0),function(c){return!!c})},rUa=function(a,b,c){function d(ia){var za=ia.hovercardButton;
if(!za)return null;za=za.subscribeButtonRenderer;if(!za)return null;var jb=f(za.unsubscribedButtonText),Gb=f(za.subscribedButtonText);if(za.subscribed){var Ra=f(za.subscriberCountWithUnsubscribeText);var rc=f(za.subscriberCountText)}else Ra=f(za.subscriberCountText),rc=f(za.subscriberCountWithSubscribeText);var Xc=null;if(ia.signinEndpoint){Xc=V0(ia,"signinEndpoint","webNavigationEndpointData","url");if(!Xc){var Hb,ke,kb;Xc=null==(Hb=za.signInEndpoint)?void 0:null==(ke=Hb.commandMetadata)?void 0:
null==(kb=ke.webCommandMetadata)?void 0:kb.url}if(!Xc)return null}return jb&&(Gb||Xc)?{subscribed:za.subscribed,subscribeText:jb,subscribeCount:Ra,unsubscribeText:Gb,unsubscribeCount:rc,enabled:za.enabled,signinUrl:Xc,classic:ia.useClassicSubscribeButton}:null}
function e(ia){if(ia){var za=[],jb=ia.videoId;jb&&za.push("v="+jb);(jb=ia.playlistId)&&za.push("list="+jb);(ia=ia.startTimeSeconds)&&za.push("t="+ia);return"/watch?"+za.join("&")}}
function f(ia){if(!ia)return null;var za=ia.simpleText;return za?za:ia.runs?g.Kl(ia.runs,function(jb){return jb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,x=null,y=!1,z=null,E=null,I=null,K=null,N=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
k){if(y=V0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):E=f(b.subscribersText)}else"WEBSITE"===k?((I=V0(l,"urlEndpoint","url"))&&(m=I),n=!0,q="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(K=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=V0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V0(b,"title","accessibility","accessibilityData","label");var aa=b.endpoint?b.endpoint.clickTrackingParams:null,
J="";if(b.metadata){var oa=f(b.metadata);oa&&(J=oa)}return{id:"element-"+c,type:k,title:f(b.title),metadata:J,callToAction:f(b.callToAction),OL:b.image,iconUrl:I,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:v,channelId:x,subscribeButton:z,subscribersText:E,isSubscribe:y,targetUrl:m||null,uV:n,sessionData:aa?{itct:aa}:null,d_:q,Qv:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:d1(b.impressionUrls||[],c1),jV:d1(b.hovercardShowUrls||[],c1),clickUrls:d1(l.loggingUrls||[],c1),visualElement:g.Dv(b.trackingParams),productPrice:K,additionalFeesText:N}},e1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:d1(a.impressionUrls||[],c1),elements:d1(a.elements||[],function(d,e){return rUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Dv(a.trackingParams));return c},f1=function(a){g.rL.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.J=0;a=a.V();this.N=g.DC(a)||g.HC(a);this.events=new g.dA(this);g.H(this,this.events);this.events.T(this.player,g.Gw("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.Hw("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.yb);this.events.T(window,"focus",this.dZ);this.load();var b=g.Wh("STYLE");(g.Oh("HEAD")[0]||document.body).appendChild(b);g.Bf(this,function(){g.$h(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},sUa=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},g1=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},tUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=e1(f,sUa(a))));h1(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Gq;d&&(c.postParams={ad_tracking:d});if(b=g.bxa(b))if(b=g.bh(b),b=g.$g(b))a.B=g.Dr(b,c)},h1=function(a,b,c){c=void 0===c?!0:c;
a.player.kf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&uUa(a);c=[];d=new g.Ew(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({G:"div",L:"ytp-ce-shadow"}),g.eL(a.player,a.u.element,4),a.C=new g.$I(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=vUa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.eL(a.player,f.element,4);var k=new g.Ew(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);wUa(a,
f,e)}else g.Ov(new g.Fs("buildEndscreenElement null",e))}a.player.Rd(c);a.yb()}},uUa=function(a){var b=g.Gv(),c=g.Hv();
c&&b&&a.endscreen.visualElement&&g.Sv(void 0,c,b,[a.endscreen.visualElement])},vUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Qv||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:i1(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:j1(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Mp(b.title||"")},oa:b.title},{G:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
oa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Qv||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:i1(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:j1(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Mp(b.title||"")},oa:b.title},{G:"div",L:"ytp-ce-playlist-count",
U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Qv||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",
U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:j1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mp(b.title||"")},oa:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:i1(b)}]};c=new g.W(c);var d=g.Ph(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.wM(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Qv||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",
U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Mp(b.title||"")},oa:b.title},{G:"div",L:"ytp-ce-website-metadata",oa:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:j1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:i1(b)},{G:"div",L:"ytp-ce-expanding-icon",W:xUa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Qv||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},
{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Mp(b.title||"")},oa:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",oa:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:j1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:i1(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",
U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.M(c.element,"ytp-ce-placeholder");return c},i1=function(a){if(a.OL)var b=a.OL.thumbnails;
return xUa(b?b[b.length-1].url:null)},xUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},wUa=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",k))}
function e(m){a.J+=m;0<a.J?(g.M(b.element,"ytp-ce-force-expand"),k1(a,c.id,!0)):(g.yp(b.element,"ytp-ce-force-expand"),g.yp(b.element,"ytp-ce-element-hover"),k1(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.Pa("mouseenter",function(){l1(a,b,c)});
b.Pa("mouseleave",function(){m1(a,b,c)});
a.player.V().isMobile||b.Pa("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){yUa(a,c,m)});
b.Pa("keypress",function(m){yUa(a,c,m)});
b.Pa("focus",function(){l1(a,b,c)});
b.Pa("blur",function(){m1(a,b,c)});
b.Pa("touchstart",function(){l1(a,b,c)});
var l=g.Rh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.yp(b.element,"ytp-ce-element-hover");g.yp(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Rh("ytp-sb-subscribe",b.element));d(g.Rh("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",k)},yUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.wp(d,"ytp-ce-element");){g.wp(d,"subscribe-label")&&n1(a,b);
if(g.wp(d,"ytp-ce-channel-subscribe"))return;d=g.ai(d)}if(!d||g.wp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])m1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.d_)n1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.bh(j1(a,b.targetUrl)),c=g.$g(c),g.zJ(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var k=j1(a,b.targetUrl),l=b.sessionData,m=g.kr(k);e&&m&&(m.v||m.list)?a.player.rk(m.v,l,m.list,!1):
g.yJ(k,l)};
n1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},j1=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.gD(a)+b}else return"";return b},l1=function(a,b,c){g.wp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),o1(a,c.jV),k1(a,c.id,!0))},m1=function(a,b,c){g.yp(b.element,"ytp-ce-element-hover");
g.yp(b.element,"ytp-ce-force-expand");k1(a,c.id,!1)},k1=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.j[e].element,"ytp-ce-element-shadow-show",c)},o1=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||g1(a))c&&c();else{b=zUa(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Kt(b[a],d)}},n1=function(a,b,c){o1(a,b.clickUrls,c);
(a=g.Hv())&&b.uV&&g.Yv(a,b.visualElement)},zUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(AUa(b[d],c));return a},AUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},BUa=function(a){return"string"===typeof a?a:""},p1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},CUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},q1=function(a){return a.value?a.value:null},r1=function(a){if(!a)return null;
var b=g.bh(BUa(a.value));b=g.$g(b);if(!b)return null;var c=p1(a.target,DUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new CUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},EUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},HUa=function(a){if(!a)return null;
var b=p1(a.type,FUa),c=p1(a.trigger,GUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=r1(a?a:null);return b?new EUa(b,c,a):null},IUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},KUa=function(a){return(a=JUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},JUa=function(a,b){return g.$b(a.action,b,void 0)},LUa=function(a,b){this.context=a;
this.j=b},t1=function(a){return a.customMessage?s1("div","iv-card-message",a.customMessage):""},u1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},v1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(s1("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},s1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Mp(c);return{G:a,W:b,oa:c}},MUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Az&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Az+");");c.dir=g.Mp(a.customMessage);var d=[{G:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,U:d}},w1=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},NUa=function(a,b){this.merchant=a;
this.price=b},OUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},PUa=function(a,b){return b?b:OUa(a)?"current":"new"},x1=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.Ya=!1;this.Sa=new Map;this.Qa=new Map;this.context.I.addEventListener(g.Gw("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Hw("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)})},y1=function(a,b,c,d,e,f,k){a.context.j.Pa(b,"click",function(l){a.pD(c,d,e,f||[],k||0,l)});
a.context.j.Pa(b,"touchstart",function(){a.Ya=!1});
a.context.j.Pa(b,"touchmove",function(){a.Ya=!0})},QUa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},z1=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
cQ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
kC:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},C1=function(a,b,c){x1.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ia=this.qb=this.B=this.isInitialized=!1;this.va=null;this.cards=[];this.ib=this.N=this.Ea=this.D=this.Ja=this.j=null;this.Z=[];this.K=this.Me=this.ya=null;this.J=0;this.xa=new g.L(function(){},c.Y.oe?4E3:3E3);
g.H(this,this.xa);this.Xa=new g.L(function(){});
g.H(this,this.Xa);this.ma=new LUa(c,function(e,f,k,l,m,n){y1(d,e,f,k,l,m,n)});
this.X=new g.W({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.X);this.C=this.X.element;this.Wa=new g.$I(this.X,330);g.H(this,this.Wa);this.jb=g.Rh("iv-drawer-header-text",this.C);this.u=g.Rh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.qb&&A1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.qb=d.B)&&B1(d)})},RUa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){A1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){B1(a)});
var c=b.headerText;g.ci(a.jb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.ya=g.Dv(b.trackingParams);a.K=g.Dv(b.closeTrackingParams);a.Me=g.Dv(b.iconTrackingParams)},SUa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Lw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:D1(a,c,b,d),sponsored:!1,tracking:z1(d,e,d.command),hm:d.trackingParams?g.Dv(d.trackingParams):null,pj:e.trackingParams?
g.Dv(e.trackingParams):null,Me:f&&f.trackingParams?g.Dv(f.trackingParams):null,imageUrl:E1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Lw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Az:null,title:d.title?g.Lw(d.title):"",customMessage:d.callToAction?g.Lw(d.callToAction):"",url:d.command.urlEndpoint.url?r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};F1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.Lw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:D1(a,c,b,d),sponsored:!1,tracking:z1(d,e,d.endpoint),hm:d.trackingParams?g.Dv(d.trackingParams):null,pj:e.trackingParams?g.Dv(e.trackingParams):null,Me:f&&f.trackingParams?
g.Dv(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Lw(d.customText):null,profileImageUrl:E1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Lw(d.channelName):"",metaInfo:[d.subscriberCountText?g.Lw(d.subscriberCountText):""],url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
F1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.Lw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:D1(a,c,b,d),sponsored:!1,tracking:z1(d,e,d.action),hm:d.trackingParams?g.Dv(d.trackingParams):
null,pj:e.trackingParams?g.Dv(e.trackingParams):null,Me:f&&f.trackingParams?g.Dv(f.trackingParams):null,Ey:E1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Lw(d.customMessage):null,playlistVideoCount:g.Lw(d.playlistVideoCount),title:d.playlistTitle?g.Lw(d.playlistTitle):"",metaInfo:[d.channelName?g.Lw(d.channelName):"",d.videoCountText?g.Lw(d.videoCountText):""],url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:QUa(d.action)})};F1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.Lw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:D1(a,c,b,d),sponsored:!1,tracking:z1(d,e,d.action),hm:d.trackingParams?g.Dv(d.trackingParams):null,pj:e.trackingParams?g.Dv(e.trackingParams):null,Me:f&&f.trackingParams?g.Dv(f.trackingParams):
null,Ey:E1(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Lw(d.lengthString):null,customMessage:d.customMessage?g.Lw(d.customMessage):null,title:d.videoTitle?g.Lw(d.videoTitle):"",metaInfo:[d.channelName?g.Lw(d.channelName):"",d.viewCountText?g.Lw(d.viewCountText):""],isLiveNow:!!d.badge,url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:QUa(d.action)})};F1(a,b)}a.J++},E1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},D1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},UUa=function(a,b){if(b=TUa(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.card.id),g.$h(b.pE),g.gc(a.cards,b),a.Ez(),G1(a)},A1=function(a,b,c){if(!a.B){a.Wa.show();
a.Ja=new g.L(function(){g.M(a.context.I.getRootNode(),g.xQ.IV_DRAWER_OPEN)},0);
a.Ja.start();a.va=g.lu(a.u,"mousewheel",function(k){a.xa.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.u.scrollTop+=k});
a.B=!0;var d=g.Hv();d&&a.ya&&a.K&&g.Wv(d,[a.ya,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.BN||(f.BN=!0,VUa(a.context.logger,f.card.tracking.impression,b)),d&&g.Wv(d,[f.card.hm]);U0(a.I);c&&(a.D=new g.L(function(){a.Ea=a.N;a.ib.focus()},330),a.D.start())}},B1=function(a){a.B&&(a.Wa.hide(),g.mu(a.va),a.va=null,g.yp(a.context.I.getRootNode(),g.xQ.IV_DRAWER_OPEN),a.B=!1,U0(a.I),a.D&&a.D.stop(),a.D=new g.L(function(){a.Ea&&(a.Ea.focus(),a.Ea=null)},330),a.D.start())},
XUa=function(a){g.xp(a.element,[g.xQ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.eL(a.I,a.C,5);WUa(a);a.N=g.Rh("ytp-cards-button",a.I.getRootNode());a.ib=g.Rh("iv-drawer-close-button",a.C);a.isInitialized=!0},WUa=function(a){var b=g.Rh("iv-drawer-close-button",a.C);
a.context.j.Pa(b,"click",a.TT,a);a.context.j.Pa(a.u,"touchend",function(){a.xa.start()});
a.context.j.Pa(a.u,"scroll",a.hU,a);a.context.u.subscribe("onHideControls",function(){a.Ia=!0});
a.context.u.subscribe("onShowControls",function(){a.Ia=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ia=g.wp(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Fu("iv-button-shown",a.EV,a));a.Z.push(g.Fu("iv-button-hidden",a.CV,a));a.Z.push(g.Fu("iv-teaser-shown",a.vS,a));a.Z.push(g.Fu("iv-teaser-hidden",a.FV,a));a.Z.push(g.Fu("iv-teaser-clicked",a.uS,a))},F1=function(a,b){a.isInitialized||XUa(a);
UUa(a,b.id);var c=YUa(a,b);if(c){var d={card:b,pE:c.element,BN:!1},e=ZUa(a,d);g.mc(a.cards,e,0,d);c.Ba(a.u,e);a.Ez();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,G1(a),$Ua(a,d),A1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&aVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){aVa(a,d)}),G1(a))}},YUa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=MUa(b);c={G:"div",Ga:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?q1(b.url)||"":""},U:[u1(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[s1("h2",void 0,b.title),d]}]}]};c=new g.W(c);w1(a,g.Qh("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ga:["iv-card","iv-card-channel"],U:[{G:"a",Ga:["iv-click-target"],W:{href:q1(b.url)||"","data-ytid":b.channelId},U:[u1(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[t1(b),{G:"h2",L:"iv-card-primary-link",oa:b.title},v1(b)]}]}]},c=new g.W(c),w1(a,g.Qh("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ga:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:q1(b.url)||""},U:[u1(b.Ey,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[t1(b),s1("h2","iv-card-primary-link",b.title),v1(b)]}]}]},c=new g.W(c),
w1(a,g.Qh("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.dc(b.offers);c=["iv-card"];d="";var f=MUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",oa:f.merchant}),f={G:"div",U:e});e=b.url?q1(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},U:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",oa:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[s1("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Wh("span");g.ci(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Bd(d,"adInfo");w1(a,g.Qh("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],oa:"LIVE NOW"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null==(c=b.url)?void 0:q1(c))||""},U:[u1(b.Ey,d),{G:"div",L:"iv-card-content",U:[t1(b),s1("h2","iv-card-primary-link",b.title),v1(b),f]}]}]},c=new g.W(e),w1(a,g.Qh("iv-click-target",
c.element),b,b.url),c;default:return null}},ZUa=function(a,b){if(0===a.cards.length)return 0;
a=g.ac(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},bVa=function(a){return a.j?"productListing"===a.j.card.type:g.Ll(a.cards,function(b){return"productListing"===b.card.type})},G1=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",bVa(a))},aVa=function(a,b){if(!g.wp(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Hv(),d=a.j?a.j.card.Me:a.Me;
c&&d&&g.Xv(c,[d]);a.j=b;G1(a)}if(c="none"!=a.element.style.display)c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d;c&&b.card.teaserDurationMs&&a.I.wu(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Xa.isActive()||((!a.B||!a.xa.isActive()&&a.Ia)&&$Ua(a,b),a.Xa.start(910+b.card.teaserDurationMs))}},$Ua=function(a,b){a.X.ub?(b=new Z0([0,
a.u.scrollTop],[0,b.pE.offsetTop],600,lUa),a.context.B.Pa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Pa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.oI(a.X,!0),a.u.scrollTop=b.pE.offsetTop,g.oI(a.X,!1))},H1=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},TUa=function(a,b){return g.$b(a.cards,function(c){return c.card.id===b})},I1=function(a,b,c){x1.call(this,a,b);
this.annotation=c;this.isActive=!1},cVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},J1=function(a,b,c){I1.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},dVa=function(a,b){var c=void 0===c?0:c;
var d=jUa(b).width;g.Jm(b,d);c=new a1(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,kUa);g.H(a,c);a.context.B.Pa(c,"begin",function(){g.Pm(b,!0)});
c.play()},gVa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.wM(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.j.Ba(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),k=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.Pm(k,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(k);g.Dm(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){eVa(a,k,l)},500);
g.H(a,a.B);a.context.j.Pa(a.element,"mouseover",function(){fVa(a,k,l,f,b.image_height)});
a.context.j.Pa(a.element,"mouseout",function(){a.B.start()})}},fVa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Om(b);a.j||(b.style.width=g.Im(f.width,!0),c.style.width=g.Im(f.width,!0));g.Dm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Dm(d,"right","1px");a.C=!0;g.Pm(b,!0);a.D=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},eVa=function(a,b,c){g.yp(a.element,"iv-branding-active");
a.J=new g.L(function(){g.Pm(b,!1);a.j||(c.style.width=g.Im(0,!0))},250);
a.J.start();a.C=!1},hVa=function(a,b,c,d,e,f,k){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.I=f;this.u=k},K1=function(a,b,c){I1.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.X=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.L(function(){d.j.setAttribute("aria-hidden","true");g.Pm(d.B,!1);g.Pm(d.u,!0)},700,this);
g.H(this,this.D)},iVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=KUa(a.annotation),f=b.image_url;if(f){var k=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",oa:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),k.appendChild(f));e&&y1(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.th(f,q1(e)),a.j=f):a.j=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
oa:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",oa:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&y1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.j,
"iv-click-target");e&&y1(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",oa:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],oa:"LIVE NOW"})),g.M(a.j,"iv-click-target"),e&&y1(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Pa(a.u,"click",function(q){L1(a,5E3,q)});
c.appendChild(a.u);g.Pm(a.u,!1);a.context.j.Pa(a.element,"mouseover",a.NU,a);a.context.j.Pa(a.element,"mouseout",a.MU,a);a.context.j.Pa(a.element,"touchend",function(q){L1(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Pa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.IU:a.HU,a);c.appendChild(a.B);g.xp(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},L1=function(a,b,c){c.stopPropagation();
jVa(a);kVa(a,b);a.j.focus()},lVa=function(a){a.isCollapsed||a.N||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},jVa=function(a){a.D.stop();
a.isCollapsed&&(g.zp(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Pm(a.u,!1),g.Pm(a.B,!0))},kVa=function(a,b){a.C||(a.C=g.xi(function(){M1(this);
lVa(this)},b,a))},M1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},mVa=function(a){this.I=a},VUa=function(a,b,c){b&&(c?N1(a,b.map(function(d){return g.ip(d,c)})):N1(a,b))},N1=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Kt(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},O1=function(a){g.rL.call(this,a);
var b=this;this.N=!1;this.loadNumber=0;this.J={};this.logger=new mVa(this.player);this.C=new g.dA(this);this.D=this.Ll=null;this.events=new g.dA(this);this.K=this.j=null;this.X=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.wS,this);this.subscribe("resize",this.rB,this);this.player.V().Z.subscribe("vast_info_card_add",this.PO,this);g.H(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.W({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.eL(this.player,this.u.element,4);this.u.hide();this.B=new g.W({G:"div",Ga:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.wr()&&this.load();var c=this.createElement({G:"style"});(g.Oh("HEAD")[0]||document.body).appendChild(c);g.Bf(this,function(){g.$h(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},nVa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.Pm(a,!1);return a},oVa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.oI(a.u,b);g.oI(a.B,b)},pVa=function(a,b,c){a.N=!0;
a.D=g.Dr(b,c)},qVa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(qVa(a,e))}return c},tVa=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.V().Z.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.sr(k)&&k.responseXML?k.responseXML:null)&&P1(a,k)}};
g.Tr()&&(d.onFinish=rVa(a,d.onFinish));d.postParams={ic_only:"1"};sVa(d,c);a.N=!0;g.Dr(b.Sa,d)}}},sVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Yv&&(a.postParams.ic_coll=b.Yv);b.Jz&&(a.postParams.ic_xml=b.Jz);b.Hy&&(a.postParams.ic_track=b.Hy)},uVa=function(a){var b=new g.W({G:"div"});
g.Pm(b.element,!1);var c=new C1(a.player,b.element,Q1(a));g.H(c,b);b.Ba(a.u.element);c.oy();return c},Q1=function(a){if(!a.K){var b=new b1(a);
g.H(a,b);var c=new g.Ek(a);g.H(a,c);a.K=new hVa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Cd)}return a.K},P1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Hv();if(e){var f=g.Gv();f&&g.Sv(void 0,e,f,[g.Dv(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=qVa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=p1(f.type,vVa),p=p1(f.style,wVa),q=BUa(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=HUa;if(null==v)var x=null;else if(g.Oa(v)){l=[];for(var y=g.r(v),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var I=f(v);x=I?[I]:[]}e=m&&n?new IUa(m,n,p,x,t):null}else e=null}catch(ia){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var K=nVa(f),N=null;switch(l.type){case "branding":if(f.player.V().Rb)break;f.u.element.appendChild(K);N=new J1(K,Q1(f),l);break;case "promotion":g.eL(f.player,K,4),N=new K1(K,Q1(f),l)}N&&N.oy();if(f=N)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=uVa(a),g.H(a,a.j));if("card"===e.type){c=a.j;var aa=e&&e.data&&e.data.card_type;
f=e.data;if(aa)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,cQ:l.teaser_impression,kC:l.teaser_click},K=f.tracking_params||{},N=null,aa){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,hm:K.card?g.Dv(K.card):null,pj:K.teaser?g.Dv(K.teaser):null,Me:K.icon?g.Dv(K.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};F1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,hm:K.card?g.Dv(K.card):
null,pj:K.teaser?g.Dv(K.teaser):null,Me:K.icon?g.Dv(K.icon):null,Ey:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};F1(c,e);break;case "productListing":f.signin_url&&(N=r1({target:"current",value:f.signin_url}));aa=[];for(var J=f.offers||[],oa=0;oa<J.length;oa++)aa.push(new NUa(g.Ih(J[oa].merchant),g.Ih(J[oa].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,hm:K.card?g.Dv(K.card):null,pj:K.teaser?g.Dv(K.teaser):null,Me:K.icon?g.Dv(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Az:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Kha:N,Jha:f.signin_title?f.signin_title:void 0,Iha:f.signin_message?f.signin_message:void 0,offers:aa};F1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,hm:K.card?g.Dv(K.card):null,pj:K.teaser?
g.Dv(K.teaser):null,Me:K.icon?g.Dv(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Az:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};F1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,hm:K.card?g.Dv(K.card):null,pj:K.teaser?g.Dv(K.teaser):null,Me:K.icon?g.Dv(K.icon):null,Ey:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},F1(c,e)}}else RUa(a.j,e);c=!0}}c&&(U0(a.player),a.rB())},xVa=function(a,
b){var c=!1;
a.j||(a.j=uVa(a),g.H(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(SUa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Lw(b.headerText):"",g.ci(c.jb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ya=b.trackingParams?g.Dv(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Dv(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Me=b.icon.infoCardIconRenderer.trackingParams?
g.Dv(b.icon.infoCardIconRenderer.trackingParams):null,U0(a.player),a.rB())},yVa=function(a,b,c,d,e){if(!a.player.V().Rb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new EUa("openUrl","click",new CUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Lw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.Lw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Lw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.Lw(b.subscriberCountWithSubscribeText)));if(b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url)var m=b.signInEndpoint.webNavigationEndpointData.url;else{var n,p;m=(null==(l=b.signInEndpoint)?void 0:null==(n=l.commandMetadata)?void 0:null==(p=n.webCommandMetadata)?void 0:p.url)||""}l={subscribeText:g.Lw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Lw(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:m};d.standalone_subscribe_button_data=l}f=new IUa(c,
"branding","branding",f,d);l=nVa(a);a.u.element.appendChild(l);f=new J1(l,Q1(a),f);f.oy();g.H(f,f);a.J[c]=f}},rVa=function(a,b){return function(){var c=g.Da.apply(0,arguments);
a.isDisposed()||a.X.push(g.mp.eg(function(){b.apply(null,g.u(c))}))}},zVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.YK.prototype.wu=g.da(19,function(a,b){var c=g.IL(this.tb());c&&c.wu(a,b)});
var W0={},X0=null;g.Wa(Z0,g.Hp);g.h=Z0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Jc())return!1;Y0(this);this.startTime=a=g.Va();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.mB();this.Ii("play");-1==this.j&&this.Ii("resume");this.j=1;var b=g.Sa(this);b in W0||(W0[b]=this);nUa();oUa(this,a);return!0};
g.h.stop=function(a){Y0(this);this.j=0;a&&(this.progress=1);pUa(this,this.progress);this.Ii("stop");this.Dx()};
g.h.pause=function(){this.Jc()&&(Y0(this),this.j=-1,this.Ii("pause"))};
g.h.ra=function(){0==this.j||this.stop(!1);this.Ii("destroy");Z0.xe.ra.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.oD=function(){this.Ii("animate")};
g.h.Ii=function(a){this.dispatchEvent(new qUa(a,this))};
g.Wa(qUa,g.Cf);g.Wa($0,Z0);$0.prototype.C=g.La;$0.prototype.oD=function(){this.C();$0.xe.oD.call(this)};
$0.prototype.Dx=function(){this.C();$0.xe.Dx.call(this)};
$0.prototype.mB=function(){this.C();$0.xe.mB.call(this)};
g.Wa(a1,$0);a1.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(b1,g.G);b1.prototype.Pa=function(a,b,c,d){c=(0,g.Ta)(c,d||this.u);a=g.lu(a,b,c);this.j.push(a);return a};
b1.prototype.XA=function(a,b,c,d){c=(0,g.Ta)(c,d||this.u);a=g.Poa(a,b,c);this.j.push(a);return a};
b1.prototype.wc=function(a){g.mu(a);g.gc(this.j,a)};
b1.prototype.ra=function(){g.mu(this.j);this.j.length=0;g.G.prototype.ra.call(this)};g.w(f1,g.rL);g.h=f1.prototype;g.h.load=function(){g.rL.prototype.load.call(this);if(!g1(this)){var a=g.cxa(this.player.getVideoData());a?(a=e1(a,sUa(this)),h1(this,a,!1)):tUa(this)}};
g.h.unload=function(){h1(this,null);this.B&&(this.B.abort(),this.B=null);g.rL.prototype.unload.call(this)};
g.h.yf=function(a,b){return g1(this)?"loadCustomEndscreenRenderer"===a?(a=e1(b,"new"),h1(this,a),!0):null:null};
g.h.getOptions=function(){return g1(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<AVa.length;f++){var k=Math.abs(b.width-AVa[f]);if(-1===e||d>=k)e=f,d=k}d=BVa[e];this.u&&g.Dm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Nm(e.element,Math.round(k.width*a.width),f);g.Jm(e.element,m,n);g.zp(e.element,CVa);m=k.left+k.width/2;k=k.top+l/2;g.M(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zp(e.element,BVa);g.M(e.element,d);(e=g.Ph(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Dm(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())o1(this,this.endscreen.impressionUrls),(a=g.Hv())&&this.endscreen.visualElement&&g.Tv(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");o1(this,c.impressionUrls);(b=g.Hv())&&g.Tv(b,c.visualElement,void 0);this.player.V().B&&this.player.Oa("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.yp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.yp(b,"ytp-ce-shown");this.player.V().B&&this.player.Oa("endscreenelementhidden",a)}};
g.h.dZ=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.zp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var AVa=[346,426,470,506,570,640,853,1280,1920],BVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),CVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var DUa={j5:"current",Gaa:"new"};var FUa={CLOSE:"close",aba:"openUrl",SUBSCRIBE:"subscribe"},GUa={K1:"click",CLOSE:"close",I6:"hidden",Eca:"rollOut",Fca:"rollOver",Bda:"shown"};var wVa={E0:"anchored",SQ:"branding",CHANNEL:"channel",i5:"cta",L6:"highlightText",n8:"label",PLAYLIST:"playlist",Wba:"popup",Lda:"speech",SUBSCRIBE:"subscribe",eea:"title",VIDEO:"video",Kfa:"website"},vVa={SQ:"branding",v1:"card",z5:"drawer",K6:"highlight",S9:"marker",gca:"promotion",TEXT:"text",pga:"widget"};g.w(x1,g.G);g.h=x1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.Ew(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Qa.set(a,e);this.context.I.Rd([a])};
g.h.oy=function(){this.context.u.subscribe("resize",this.Ez,this)};
g.h.pD=function(a,b,c,d,e,f){if(this.Ya)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.$h(this.element)};
g.h.Ez=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=q1(a);if(f){var k=PUa(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.kr(f||"");m&&n&&(n.v||n.list)?e.context.I.rk(n.v,b,n.list,!1):g.zJ(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);N1(this.context.logger,c,l,d);OUa(f)||(c=g.Hv(),d=b.itct,c&&d&&g.Yv(c,g.Dv(d)))}};
g.h.ra=function(){this.Sa.clear();this.Qa.clear();g.G.prototype.ra.call(this)};
g.h.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.w(C1,x1);g.h=C1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Om(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Ez=function(){var a=this.isAvailable();g.Pm(this.element,a);g.O(this.context.I.getRootNode(),g.xQ.IV_DRAWER_ENABLED,a);U0(this.I)};
g.h.destroy=function(){this.I.wu(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Gu(this.Z);g.mu(this.va);this.Ja&&this.Ja.dispose();this.D&&this.D.dispose();x1.prototype.destroy.call(this)};
g.h.TT=function(){if(this.B){N1(this.context.logger,H1(this).tracking.close);var a=g.Hv();a&&this.K&&g.Yv(a,this.K);B1(this)}};
g.h.hU=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.EV=function(){var a=g.Hv(),b=H1(this);b=b?b.Me:this.Me;a&&b&&g.Wv(a,[b])};
g.h.CV=function(){var a=g.Hv(),b=H1(this);b=b?b.Me:this.Me;a&&b&&g.Xv(a,[b])};
g.h.vS=function(){var a=H1(this);N1(this.context.logger,a.tracking.cQ);var b=g.Hv();b&&a&&g.Wv(b,[a.pj,a.Me])};
g.h.FV=function(){var a=g.Hv(),b=H1(this);a&&b&&g.Xv(a,[b.pj])};
g.h.uS=function(a){var b=H1(this),c=g.Hv();this.j?a?(a=this.context.logger,N1(a,b.tracking.kC),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.pj&&g.Yv(c,b.pj)):(a=this.context.logger,N1(a,b.tracking.kC),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Me&&g.Yv(c,b.Me)):(a=this.context.logger,N1(a,b.tracking.kC),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Me&&g.Yv(c,this.Me))};g.w(I1,x1);I1.prototype.oy=function(){x1.prototype.oy.call(this);cVa(this)};
I1.prototype.show=function(){x1.prototype.show.call(this);var a=g.Hv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Wv(a,[g.Dv(b.itct)])};
I1.prototype.hide=function(){x1.prototype.hide.call(this);var a=g.Hv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Xv(a,[g.Dv(b.itct)])};g.w(J1,I1);
J1.prototype.show=function(){if(!this.isActive){I1.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Pm(this.u,!1);var b=this.context.Y.S("html5_player_branding_button_killswitch")?this.createElement({G:"div",Ga:["branding-img-container"]}):this.createElement({G:"button",Ga:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=KUa(this.annotation);c&&(b=this.context.Y.S("html5_player_branding_button_killswitch")?this.u:b,y1(this,b,c,this.annotation.id,a.session_data));gVa(this,a);this.K=!0}g.Pm(this.element,!0);this.isActive=!0;this.u&&dVa(this,this.u)}};
J1.prototype.hide=function(){this.isActive&&(I1.prototype.hide.call(this),g.Pm(this.element,!1),this.isActive=!1)};
J1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);I1.prototype.destroy.call(this)};g.w(K1,I1);g.h=K1.prototype;g.h.show=function(){this.isActive||(I1.prototype.show.call(this),this.X||(iVa(this),this.X=!0),g.Pm(this.element,!0),g.xi(function(){g.yp(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,M1(this),jVa(this),kVa(this,this.J))};
g.h.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.pD=function(a,b,c,d,e,f){return this.isCollapsed?!1:I1.prototype.pD.call(this,a,b,c,d,e,f)};
g.h.NU=function(a){this.N=!0;L1(this,500,a)};
g.h.MU=function(){this.N=!1;lVa(this)};
g.h.HU=function(a){a.stopPropagation();this.hide()};
g.h.IU=function(a){a.stopPropagation();M1(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();I1.prototype.destroy.call(this)};g.w(O1,g.rL);g.h=O1.prototype;g.h.yf=function(a,b){if(!zVa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.s_(b))&&P1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(UUa(this.j,b),U0(this.player)),!0}return null};
g.h.getOptions=function(){return zVa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.wr=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.XN||a.Z.get(b.videoId)||g.wE(b)||g.xE(b)?!0:!1};
g.h.rB=function(){if(this.B){var a=this.player.eb().getVideoContentRect(!0);g.Nm(this.B.element,a.width,a.height);g.Jm(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Kj();a=this.j;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.h.wS=function(a){oVa(this,a.state);g.V(a.state,2)&&(this.Lh()&&this.Rk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.wu(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.sr(k)&&k.responseXML?k.responseXML:null)&&(P1(b,k),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.rL.prototype.load.call(this);oVa(this,this.player.zb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Tr()&&(a=rVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().Z.get(d);f&&sVa(e,f);f=f&&(f.Jz||f.Yv);if(!c.cm||f)c.Sa?pVa(this,c.Sa,e):(this.Ll=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Ll));
g.eL(this.player,this.B.element,4);this.rB();(f=g.wE(c))&&xVa(this,f);(f=g.xE(c))&&f.featuredChannel&&yVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.Ll&&(this.player.removeEventListener("videodatachange",this.Ll),this.Ll=null),pVa(this,b.Sa,a))};
g.h.unload=function(){this.player.kf("annotations_module");for(var a=g.r(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.j&&(this.j.destroy(),this.j=null,U0(this.player));this.N=!1;this.D&&(this.D.abort(),this.D=null);this.J={};this.u.hide();g.rL.prototype.unload.call(this);this.B.detach();this.Ll&&(this.player.removeEventListener("videodatachange",this.Ll),this.Ll=null)};
g.h.PO=function(a){a===this.player.getVideoData().videoId&&(this.loaded?tVa(this):this.load())};
g.h.Lh=function(){return!!this.j&&this.j.isAvailable()};
g.h.Rk=function(){this.Lh();return!!this.j&&this.j.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Lh();this.j&&(a?c?A1(this.j,c,b):A1(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):B1(this.j))};
g.h.wu=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.ra=function(){this.player.V().Z.unsubscribe("vast_info_card_add",this.PO,this);g.yp(this.player.getRootNode(),g.xQ.IV_DRAWER_OPEN);for(var a=this.X,b=g.mp,c=0,d=a.length;c<d;c++)b.Fi(a[c]);this.X.length=0;g.rL.prototype.ra.call(this)};
g.h.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.qL("annotations_module",O1);g.qL("creatorendscreen",f1);})(_yt_player);
